export interface PartitionInfo {
  name: string;
  category: 'boot' | 'firmware' | 'logical' | 'data';
  groupLabel: string;
  summary: string;
  technicalRole: string;
  bootStage: string;
  avbStatus: string;
  chipset: 'Qualcomm' | 'MediaTek' | 'Universal';
  flashingMode: 'bootloader (fastboot)' | 'userspace (fastbootd)' | 'non-flashable';
  archiveFile: string;
  rootRelevance?: string;
}

export interface PartitionGroupConfig {
  id: string;
  title: string;
  badge?: string;
  isSuperContainer?: boolean;
  isFirmwareContainer?: boolean;
  superTitle?: string;
  description?: string;
  keys: PartitionKey[];
}

export interface AbStepConfig {
  step: number;
  title: string;
  badge: string;
  activeSlot: 'A' | 'B';
  targetSlot: 'A' | 'B';
  statusA: string;
  statusB: string;
  operation: string;
  technicalDetails: string;
  command: string;
}

export interface AospDocLink {
  title: string;
  url: string;
  desc: string;
}

export const PARTITIONS_DATA = {
  // --- 1. CORE BOOT & AVB 2.0 STACK ---
  boot: {
    name: 'boot',
    category: 'boot',
    groupLabel: 'Core Boot & Kernel Stack',
    summary: 'Houses the Android Generic Kernel Image (GKI) Linux kernel binary (and boot ramdisk on Phone 1 and Phone 2).',
    technicalRole: 'Contains the pure Generic Kernel Image (GKI) Linux kernel binary loaded into RAM during early execution. On Phone (1) and Phone (2), it also holds the boot ramdisk; on newer models (Phone 2a, Phone 3, CMF series), userspace ramdisk is separated into init_boot.',
    bootStage: 'Stage 3 (Loaded by ABL / Little Kernel into RAM)',
    avbStatus: 'Verified by vbmeta cryptographic hash descriptor',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: '-image-boot.7z',
    rootRelevance: 'Primary root patch target on Phone (1) and Phone (2); on newer models with init_boot, patch init_boot instead.',
  },
  init_boot: {
    name: 'init_boot',
    category: 'boot',
    groupLabel: 'Core Boot & Kernel Stack',
    summary: 'Houses the generic boot ramdisk and early userspace init on modern devices (Phone 2a, Phone 3, CMF series).',
    technicalRole: 'Contains the generic rootfs, early init binary, and first-stage mount configurations. Present on Phone (2a/Plus), Phone (3), Phone (4 series), and CMF devices; omitted on Phone (1) and Phone (2) where ramdisk resides in boot.',
    bootStage: 'Stage 3 (Parsed by kernel during early boot)',
    avbStatus: 'Verified by vbmeta cryptographic hash descriptor',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: '-image-boot.7z',
    rootRelevance: 'Primary root patch target (Magisk, KernelSU, APatch) on devices with init_boot. For Phone (1) and Phone (2), patch boot instead.',
  },
  vendor_boot: {
    name: 'vendor_boot',
    category: 'boot',
    groupLabel: 'Core Boot & Kernel Stack',
    summary: 'Contains SoC-specific vendor ramdisk modules, board devicetrees, and recovery ramdisk on MediaTek devices.',
    technicalRole: 'Stores vendor kernel modules, early driver initialization binaries, and board devicetrees. On MediaTek devices (Phone 2a, CMF series), it also houses the recovery ramdisk in place of a standalone physical recovery partition.',
    bootStage: 'Stage 3 (Supplements generic ramdisk at boot)',
    avbStatus: 'Verified by vbmeta cryptographic hash descriptor',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: '-image-boot.7z',
  },
  dtbo: {
    name: 'dtbo',
    category: 'boot',
    groupLabel: 'Core Boot & Kernel Stack',
    summary: 'Device Tree Blob Overlay table for board-level hardware revisions.',
    technicalRole: 'Applies runtime hardware overlays onto the base kernel device tree for display panel variants, pin muxing, and PMIC circuits.',
    bootStage: 'Stage 2 (Loaded before kernel handover)',
    avbStatus: 'Verified by vbmeta and bootloader (ABL on Qualcomm / LK on MediaTek)',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: '-image-boot.7z',
  },
  recovery: {
    name: 'recovery',
    category: 'boot',
    groupLabel: 'Core Boot & Kernel Stack',
    summary: 'Standalone recovery partition hosting FastbootD and recovery maintenance on Qualcomm devices.',
    technicalRole: 'Provides maintenance tools for factory data reset, sideload updates, and FastbootD userspace flashing. Retained as a physical partition on Qualcomm Snapdragon models (Phone 1, 2, 3, 4a); on MediaTek models, recovery is integrated into vendor_boot.',
    bootStage: 'Standalone Boot Mode (Invoked via keycombo / adb reboot recovery)',
    avbStatus: 'Verified by vbmeta hash descriptor',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-boot.7z',
  },
  vbmeta: {
    name: 'vbmeta',
    category: 'boot',
    groupLabel: 'Android Verified Boot (AVB 2.0)',
    summary: 'Cryptographic root of trust containing public keys and partition descriptor hashes.',
    technicalRole: 'Houses top-level AVB metadata, rollback index tables, and SHA-256 hash trees for all slotted boot and system images.',
    bootStage: 'Stage 2 (Validated by ABL/LK before booting kernel)',
    avbStatus: 'Root of Trust (Enforces dm-verity across system)',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: '-image-boot.7z',
    rootRelevance: 'Flashing custom ROMs or modified images often requires disabling verification flags in vbmeta.',
  },
  vbmeta_system: {
    name: 'vbmeta_system',
    category: 'boot',
    groupLabel: 'Android Verified Boot (AVB 2.0)',
    summary: 'Chained cryptographic descriptor verifying the dynamic system partition.',
    technicalRole: 'Contains the dm-verity hash tree root and signature for the logical system filesystem.',
    bootStage: 'Stage 3 (Validated when dm-linear maps system)',
    avbStatus: 'Chained AVB 2.0 Descriptor',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: '-image-boot.7z',
  },
  vbmeta_vendor: {
    name: 'vbmeta_vendor',
    category: 'boot',
    groupLabel: 'Android Verified Boot (AVB 2.0)',
    summary: 'Chained cryptographic descriptor verifying vendor HAL images.',
    technicalRole: 'Contains the dm-verity root hash and signature for the vendor filesystem.',
    bootStage: 'Stage 3 (Validated when dm-linear maps vendor)',
    avbStatus: 'Chained AVB 2.0 Descriptor',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: '-image-boot.7z',
  },

  // --- 2. DYNAMIC LOGICAL PARTITIONS (super.img) ---
  system: {
    name: 'system',
    category: 'logical',
    groupLabel: 'Dynamic Logical Partition (super.img)',
    summary: 'AOSP core operating system framework, system binaries, and runtime libraries.',
    technicalRole: 'Contains the core Android runtime (ART), system services, base utilities, and public APIs mounted read-only via dm-linear.',
    bootStage: 'Stage 4 (Userspace init launch)',
    avbStatus: 'Protected by dm-verity hash tree in vbmeta_system',
    flashingMode: 'userspace (fastbootd)',
    chipset: 'Universal',
    archiveFile: '-image-logical.7z.001-00x',
  },
  system_ext: {
    name: 'system_ext',
    category: 'logical',
    groupLabel: 'Dynamic Logical Partition (super.img)',
    summary: 'OEM framework extensions and system service additions.',
    technicalRole: 'Provides Nothing OS framework APIs and system services that extend generic AOSP without modifying standard system libraries.',
    bootStage: 'Stage 4 (Userspace init launch)',
    avbStatus: 'Protected by dm-verity',
    flashingMode: 'userspace (fastbootd)',
    chipset: 'Universal',
    archiveFile: '-image-logical.7z.001-00x',
  },
  product: {
    name: 'product',
    category: 'logical',
    groupLabel: 'Dynamic Logical Partition (super.img)',
    summary: 'OEM product-specific software, system UI overlays, and custom device services.',
    technicalRole: 'Houses product-specific software including Nothing OS system applications (Nothing Launcher, Camera, Glyph Interface services), custom fonts, and Runtime Resource Overlays (RRO).',
    bootStage: 'Stage 4 (Userspace app launch)',
    avbStatus: 'Protected by dm-verity',
    flashingMode: 'userspace (fastbootd)',
    chipset: 'Universal',
    archiveFile: '-image-logical.7z.001-00x',
  },
  vendor: {
    name: 'vendor',
    category: 'logical',
    groupLabel: 'Dynamic Logical Partition (super.img)',
    summary: 'Hardware Abstraction Layer (HAL) implementations and SoC drivers.',
    technicalRole: 'Contains proprietary chipset driver daemons, HIDL/AIDL HAL interfaces for camera ISP, audio DSP, display rendering, and sensors.',
    bootStage: 'Stage 4 (Vendor init & HAL launch)',
    avbStatus: 'Protected by dm-verity hash tree in vbmeta_vendor',
    flashingMode: 'userspace (fastbootd)',
    chipset: 'Universal',
    archiveFile: '-image-logical.7z.001-00x',
  },
  odm: {
    name: 'odm',
    category: 'logical',
    groupLabel: 'Dynamic Logical Partition (super.img)',
    summary: 'Original Design Manufacturer board configurations and sensor tunings.',
    technicalRole: 'Houses board-specific customizations, camera sensor calibrations, acoustic audio profiles, and device variant overrides.',
    bootStage: 'Stage 4 (Vendor init launch)',
    avbStatus: 'Protected by dm-verity',
    flashingMode: 'userspace (fastbootd)',
    chipset: 'Universal',
    archiveFile: '-image-logical.7z.001-00x',
  },
  vendor_dlkm: {
    name: 'vendor_dlkm',
    category: 'logical',
    groupLabel: 'Dynamic Logical Partition (super.img)',
    summary: 'Dynamically Loadable Kernel Modules for vendor hardware drivers.',
    technicalRole: 'Stores loadable `.ko` kernel modules (touchscreen controller, display panel, audio codec) loaded dynamically by vendor init.',
    bootStage: 'Stage 3 / 4 (Early kernel module insertion)',
    avbStatus: 'Protected by dm-verity',
    flashingMode: 'userspace (fastbootd)',
    chipset: 'Universal',
    archiveFile: '-image-logical.7z.001-00x',
  },
  system_dlkm: {
    name: 'system_dlkm',
    category: 'logical',
    groupLabel: 'Dynamic Logical Partition (super.img)',
    summary: 'Dynamically Loadable Kernel Modules for core GKI system services.',
    technicalRole: 'Houses core Generic Kernel Image loadable modules that match the specific GKI kernel release.',
    bootStage: 'Stage 3 (Generic kernel module insertion)',
    avbStatus: 'Protected by dm-verity',
    flashingMode: 'userspace (fastbootd)',
    chipset: 'Universal',
    archiveFile: '-image-logical.7z.001-00x',
  },
  odm_dlkm: {
    name: 'odm_dlkm',
    category: 'logical',
    groupLabel: 'Dynamic Logical Partition (super.img)',
    summary: 'Dynamically Loadable Kernel Modules for ODM-specific peripherals.',
    technicalRole: 'Stores board-specific peripheral driver modules loaded dynamically on MediaTek variants (Phone 2a / Plus, CMF series).',
    bootStage: 'Stage 3 / 4 (ODM peripheral driver insertion)',
    avbStatus: 'Protected by dm-verity',
    flashingMode: 'userspace (fastbootd)',
    chipset: 'MediaTek',
    archiveFile: '-image-logical.7z.001-00x',
  },

  // --- 3. QUALCOMM SNAPDRAGON FIRMWARE ---
  abl: {
    name: 'abl',
    category: 'firmware',
    groupLabel: 'Snapdragon Bootloader Firmware',
    summary: 'Android BootLoader on Snapdragon platforms providing Fastboot interface.',
    technicalRole: 'Second-stage bootloader. Initializes display engine, implements Fastboot USB protocol, validates vbmeta signatures, and jumps to kernel.',
    bootStage: 'Stage 2 (Second-stage bootloader)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  xbl: {
    name: 'xbl',
    category: 'firmware',
    groupLabel: 'Snapdragon Bootloader Firmware',
    summary: 'eXtensible BootLoader initializing PMIC and LPDDR RAM training.',
    technicalRole: 'First-stage bootloader initialized by Primary Boot ROM (PBL). Configures clock trees, power management ICs, and DDR memory channels.',
    bootStage: 'Stage 1 (First-stage bootloader)',
    avbStatus: 'Signed with Qualcomm Secure Boot key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  xbl_config: {
    name: 'xbl_config',
    category: 'firmware',
    groupLabel: 'Snapdragon Bootloader Firmware',
    summary: 'Configuration parameters and memory timing tables for XBL.',
    technicalRole: 'Supplies hardware-specific DDR timings and PMIC configuration parameters to the primary XBL bootloader binary.',
    bootStage: 'Stage 1 (Read by XBL on power-on)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  xbl_ramdump: {
    name: 'xbl_ramdump',
    category: 'firmware',
    groupLabel: 'Snapdragon Bootloader Firmware',
    summary: 'First-stage crash log and RAM dump collection handler.',
    technicalRole: 'Captures DDR register states and early boot crash context to aid debugging before main bootloader initialization.',
    bootStage: 'Stage 1 (Crash dump handler)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  tz: {
    name: 'tz',
    category: 'firmware',
    groupLabel: 'Snapdragon Security Firmware (TrustZone)',
    summary: 'Qualcomm Secure Execution Environment (QSEE / TrustZone) OS.',
    technicalRole: 'Hardware-isolated secure operating system executing DRM key storage, biometric fingerprint matching, and hardware Keymaster keystore.',
    bootStage: 'Stage 1 / 2 (Secure world initialization)',
    avbStatus: 'Signed with Qualcomm Root Key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  hyp: {
    name: 'hyp',
    category: 'firmware',
    groupLabel: 'Snapdragon Security Firmware (Hypervisor)',
    summary: 'Qualcomm EL2 hypervisor firmware enforcing memory isolation.',
    technicalRole: 'Enforces hardware memory boundary separation between TrustZone, Android Linux kernel, modem, and subsystem processors.',
    bootStage: 'Stage 1 / 2 (EL2 hypervisor launch)',
    avbStatus: 'Signed with Qualcomm Root Key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  modem: {
    name: 'modem',
    category: 'firmware',
    groupLabel: 'SoC Baseband Firmware',
    summary: 'Baseband cellular processor software on Snapdragon and modern MediaTek models.',
    technicalRole: 'Dedicated real-time cellular modem firmware managing 5G NR, LTE, VoLTE, VoWiFi, and RF calibrations. Used on Qualcomm Snapdragon devices and modern MediaTek models (CMF Phone 1, CMF Phone 2 Pro, Phone 3a Lite), replacing md1img.',
    bootStage: 'Stage 2 (Loaded onto modem DSP)',
    avbStatus: 'Signed with SoC vendor radio key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: '-image-firmware.7z',
  },
  dsp: {
    name: 'dsp',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'Hexagon DSP compute engine firmware for audio, neural processing, and sensor processing.',
    technicalRole: 'Executes Qualcomm Hexagon DSP compute routines for real-time camera AI pipelines, voice processing, and sensor fusion.',
    bootStage: 'Stage 2 / 3 (Subsystem firmware loading)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  keymaster: {
    name: 'keymaster',
    category: 'firmware',
    groupLabel: 'Snapdragon Security Firmware',
    summary: 'Hardware-backed cryptographic Keymaster enclave applet.',
    technicalRole: 'Runs inside TrustZone to provide hardware key generation, RSA/ECC signing, gatekeeper auth tokens, and disk encryption key management.',
    bootStage: 'Stage 2 (TrustZone secure service launch)',
    avbStatus: 'Signed with Qualcomm Root Key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  pvmfw: {
    name: 'pvmfw',
    category: 'firmware',
    groupLabel: 'Android Virtualization Framework (pKVM)',
    summary: 'Protected Virtual Machine Firmware for Android Virtualization Framework (pKVM).',
    technicalRole: 'Provides cryptographic isolation and early booting for Microdroid protected virtual machines. Standard AOSP partition available across Snapdragon and high-end MediaTek platforms.',
    bootStage: 'Stage 2 (Hypervisor VM initialization)',
    avbStatus: 'Verified by Android AVF / hypervisor key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: '-image-firmware.7z',
  },
  qupfw: {
    name: 'qupfw',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'Qualcomm Universal Peripheral firmware for I2C, SPI, and UART busses.',
    technicalRole: 'Micro-engine firmware controlling hardware communication bridges to touchscreen controllers, haptic drivers, and sensor ICs.',
    bootStage: 'Stage 1 / 2 (Low-level bus initialization)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  uefi: {
    name: 'uefi',
    category: 'firmware',
    groupLabel: 'Snapdragon Bootloader Firmware',
    summary: 'Unified Extensible Firmware Interface core boot environment on Qualcomm platforms.',
    technicalRole: 'Provides standardized UEFI runtime services, hardware initialization, and early platform services.',
    bootStage: 'Stage 2 (UEFI boot services)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  uefisecapp: {
    name: 'uefisecapp',
    category: 'firmware',
    groupLabel: 'Snapdragon Security Firmware',
    summary: 'UEFI Secure Application runtime managing authenticated variables and RPMB.',
    technicalRole: 'Executes secure world operations for UEFI secure boot variable storage, anti-rollback checks, and key provisioning in TrustZone.',
    bootStage: 'Stage 2 (Loaded inside TrustZone / UEFI secure world)',
    avbStatus: 'Signed with Qualcomm Root Key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  aop: {
    name: 'aop',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'Always-On Processor firmware managing system sleep states and power rails.',
    technicalRole: 'Dedicated microcontroller managing low-power sleep transitions, clock gating, and SoC thermal limits.',
    bootStage: 'Stage 1 (Power-on controller startup)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  aop_config: {
    name: 'aop_config',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'Always-On Processor configuration parameters and power rail limits on Phone (3) and Phone (4a) Pro.',
    technicalRole: 'Stores board-specific power rail mappings and wake-up interrupt assignments used by the AOP core on newer platforms.',
    bootStage: 'Stage 1 (Loaded alongside AOP image)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  cpucp: {
    name: 'cpucp',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'CPU Co-Processor power and frequency scaling firmware.',
    technicalRole: 'Controls autonomous CPU cluster frequency scaling, hardware energy profiles, and per-core voltage regulation.',
    bootStage: 'Stage 1 (CPU voltage regulation setup)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  cpucp_dtb: {
    name: 'cpucp_dtb',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'CPU Co-Processor Device Tree Blob for per-cluster operating points on Phone (3) and Phone (4a) Pro.',
    technicalRole: 'Supplies hardware operating performance points (OPP) and thermal throttling curves for CPU clusters.',
    bootStage: 'Stage 1 (Parsed during CPUCP initialization)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  devcfg: {
    name: 'devcfg',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'Device Configuration binary detailing hardware subsystem parameters.',
    technicalRole: 'Defines memory mappings, interrupt routing, and hardware capability descriptors for TrustZone and kernel drivers.',
    bootStage: 'Stage 1 / 2 (Read during TZ / bootloader startup)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  featenabler: {
    name: 'featenabler',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'Qualcomm hardware feature licensing verification binary.',
    technicalRole: 'Validates hardware cryptographic fuse entitlements for modem capabilities, 5G carrier aggregation, and multimedia codecs.',
    bootStage: 'Stage 2 (Subsystem entitlement validation)',
    avbStatus: 'Signed with Qualcomm Root Key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  imagefv: {
    name: 'imagefv',
    category: 'firmware',
    groupLabel: 'Snapdragon Security Firmware',
    summary: 'Image Fuse Verification binary validating secure boot hardware hashes.',
    technicalRole: 'Checks software signature public key digests against electronic fuse (eFuse) values burned onto the physical SoC silicon.',
    bootStage: 'Stage 1 (Hardware root of trust validation)',
    avbStatus: 'Hardware eFuse anchored',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  shrm: {
    name: 'shrm',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'Shared Resource Manager firmware coordinating memory arbitration.',
    technicalRole: 'Arbitrates high-bandwidth memory access and QoS bandwidth priorities between GPU, Camera ISP, and display engine.',
    bootStage: 'Stage 1 / 2 (Memory interconnect setup)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  bluetooth: {
    name: 'bluetooth',
    category: 'firmware',
    groupLabel: 'Snapdragon Connectivity Firmware',
    summary: 'Qualcomm Bluetooth controller firmware binary and RF calibration tables.',
    technicalRole: 'Contains low-level Bluetooth baseband stack firmware loaded onto Qualcomm FastConnect / WCNSS wireless connectivity hardware. Not present on MediaTek devices.',
    bootStage: 'Stage 3 (Loaded during Bluetooth daemon initialization)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  multiimgoem: {
    name: 'multiimgoem',
    category: 'firmware',
    groupLabel: 'Snapdragon Bootloader Firmware',
    summary: 'OEM multi-image descriptor table containing cryptographic signing metadata.',
    technicalRole: 'Supplies hash lists and certificate chains used by the bootloader to authenticate multiple firmware images in a single pass.',
    bootStage: 'Stage 1 / 2 (Firmware authentication check)',
    avbStatus: 'Signed with OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  multiimgqti: {
    name: 'multiimgqti',
    category: 'firmware',
    groupLabel: 'Snapdragon Bootloader Firmware',
    summary: 'Qualcomm Technologies Inc multi-image descriptor table containing reference signature hashes.',
    technicalRole: 'Contains Qualcomm reference hash certificates used alongside multiimgoem for fast multi-binary authentication on Phone (3) and Phone (4a) Pro.',
    bootStage: 'Stage 1 / 2 (Firmware authentication check)',
    avbStatus: 'Signed with Qualcomm QTI Key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  qweslicstore: {
    name: 'qweslicstore',
    category: 'firmware',
    groupLabel: 'Snapdragon Security Firmware',
    summary: 'Qualcomm Wireless Edge Services license store partition.',
    technicalRole: 'Houses cryptographic certificates and hardware capability licenses for premium modem and multimedia features.',
    bootStage: 'Stage 2 (License verification during boot)',
    avbStatus: 'Signed with Qualcomm Root Key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  soccp_dcd: {
    name: 'soccp_dcd',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'SoC Co-Processor Dynamic Clock and Power Control subsystem firmware.',
    technicalRole: 'Regulates dynamic clock switching and low-latency power rail transitions for core subsystems.',
    bootStage: 'Stage 1 / 2 (Power controller initialization)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },
  soccp_debug: {
    name: 'soccp_debug',
    category: 'firmware',
    groupLabel: 'Snapdragon Subsystem Firmware',
    summary: 'SoC Co-Processor hardware diagnostic and debug tracing configuration on Phone (3) and Phone (4a) Pro.',
    technicalRole: 'Maintains non-volatile trace logs and power rail telemetry registers for hardware debugging.',
    bootStage: 'Stage 1 / 2 (Debug instrumentation setup)',
    avbStatus: 'Signed with Qualcomm OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Qualcomm',
    archiveFile: '-image-firmware.7z',
  },

  // --- 4. MEDIATEK DIMENSITY FIRMWARE ---
  preloader_raw: {
    name: 'preloader_raw',
    category: 'firmware',
    groupLabel: 'MediaTek Bootloader Firmware',
    summary: 'Primary hardware bootloader on MediaTek Dimensity processors.',
    technicalRole: 'Loaded directly by the MediaTek Boot ROM on power-on. Initializes system clocks, PMIC power rails, and LPDDR RAM before loading Little Kernel.',
    bootStage: 'Stage 1 (First-stage bootloader)',
    avbStatus: 'Signed with MediaTek Secure Boot key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  lk: {
    name: 'lk',
    category: 'firmware',
    groupLabel: 'MediaTek Bootloader (Little Kernel)',
    summary: 'Second-stage bootloader providing Fastboot mode on MediaTek platforms.',
    technicalRole: 'Implements Fastboot mode, AVB signature verification, display logo initialization, and kernel boot execution on Dimensity chips.',
    bootStage: 'Stage 2 (Second-stage bootloader)',
    avbStatus: 'Signed with MediaTek OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  tee: {
    name: 'tee',
    category: 'firmware',
    groupLabel: 'MediaTek Security Firmware',
    summary: 'Trusted Execution Environment secure OS on MediaTek platforms.',
    technicalRole: 'Hardware-isolated secure OS managing biometric authentication, Widevine L1 cryptographic keys, and gatekeeper security tokens.',
    bootStage: 'Stage 1 / 2 (Secure world init)',
    avbStatus: 'Signed with MediaTek Secure Key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  md1img: {
    name: 'md1img',
    category: 'firmware',
    groupLabel: 'MediaTek Baseband Firmware',
    summary: 'MediaTek 5G / 4G LTE cellular baseband modem firmware image on Phone (2a) and Phone (2a) Plus.',
    technicalRole: 'Dedicated baseband firmware executing on the MediaTek modem DSP for cellular protocol stacks on Dimensity 7200/7350 Pro devices (Pacman / PacmanPro). Newer MediaTek models name this partition modem.',
    bootStage: 'Stage 2 (MediaTek modem DSP initialization)',
    avbStatus: 'Signed with MediaTek modem key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  connsys_bt: {
    name: 'connsys_bt',
    category: 'firmware',
    groupLabel: 'MediaTek Connectivity Firmware',
    summary: 'MediaTek Connectivity Subsystem Bluetooth controller firmware and RF calibration.',
    technicalRole: 'Runs dedicated Bluetooth protocol stacks and baseband controls on integrated MediaTek connectivity hardware (MT66xx). Replaces Qualcomm standalone bluetooth partition on MediaTek devices.',
    bootStage: 'Stage 3 (Loaded during Bluetooth daemon initialization)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  connsys_wifi: {
    name: 'connsys_wifi',
    category: 'firmware',
    groupLabel: 'MediaTek Connectivity Firmware',
    summary: 'MediaTek Connectivity Subsystem Wi-Fi controller firmware.',
    technicalRole: 'Contains MAC layer and physical baseband firmware for high-throughput Wi-Fi 6 / 6E operation on MediaTek platforms.',
    bootStage: 'Stage 3 (Loaded during Wi-Fi HAL startup)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  connsys_gnss: {
    name: 'connsys_gnss',
    category: 'firmware',
    groupLabel: 'MediaTek Connectivity Firmware',
    summary: 'MediaTek Global Navigation Satellite System positioning firmware.',
    technicalRole: 'Processes satellite signal acquisition, ephemeris data, and positioning algorithms for GPS, GLONASS, Galileo, and BeiDou.',
    bootStage: 'Stage 3 (Loaded by location HAL)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  audio_dsp: {
    name: 'audio_dsp',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'MediaTek Audio DSP firmware for hardware sound processing and codec decoding.',
    technicalRole: 'Executes real-time audio equalization, speaker protection algorithms, and voice acoustic echo cancellation on the dedicated MediaTek audio DSP.',
    bootStage: 'Stage 3 (Loaded during audio server startup)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  mvpu_algo: {
    name: 'mvpu_algo',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'MediaTek Vision Processing Unit computer vision and photography algorithms.',
    technicalRole: 'Houses computer vision and deep learning models for real-time depth mapping, HDR capture, and camera ISP optimizations.',
    bootStage: 'Stage 3 (Camera ISP initialization)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  scp: {
    name: 'scp',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'System Companion Processor managing sensor hub and low-power audio.',
    technicalRole: 'Controls always-on accelerometer, gyroscope, proximity sensors, and ambient light processing without waking main CPU cores.',
    bootStage: 'Stage 2 (Sensor hub initialization)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  apusys: {
    name: 'apusys',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'AI Processing Unit (APU / NPU) system firmware for camera AI compute.',
    technicalRole: 'Powers MediaTek NeuroPilot hardware for real-time computational photography, scene recognition, and neural network acceleration.',
    bootStage: 'Stage 3 (APU driver initialization)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  gz: {
    name: 'gz',
    category: 'firmware',
    groupLabel: 'MediaTek Security Firmware (GenieZone)',
    summary: 'MediaTek micro-kernel hypervisor security isolate (GenieZone).',
    technicalRole: 'Provides virtualization-based security (VBS) and isolated execution environments for biometric matching and Android keymint.',
    bootStage: 'Stage 1 / 2 (Hypervisor initialization)',
    avbStatus: 'Signed with MediaTek Secure Key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  ccu: {
    name: 'ccu',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'Camera Control Unit firmware for fast 3A autofocus and auto-exposure.',
    technicalRole: 'Embedded microcontroller directly inside the camera ISP executing hardware autofocus and auto-exposure algorithms with zero CPU latency.',
    bootStage: 'Stage 3 (Camera ISP initialization)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  dpm: {
    name: 'dpm',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'Dynamic Power Management controller firmware.',
    technicalRole: 'Manages dynamic voltage and frequency scaling (DVFS) curves across CPU, GPU, and DRAM memory buses.',
    bootStage: 'Stage 1 (Power controller initialization)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  gpueb: {
    name: 'gpueb',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'GPU Execution Block firmware controlling Mali/Immortalis graphics core.',
    technicalRole: 'Manages low-level GPU power gating, hardware shader scheduling, and thermal throttling limits.',
    bootStage: 'Stage 3 (GPU driver initialization)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  vcp: {
    name: 'vcp',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'Video Core Processor firmware for hardware 4K video encoding/decoding.',
    technicalRole: 'Powers dedicated hardware codecs for HEVC, AV1, and VP9 video stream processing.',
    bootStage: 'Stage 3 (Media codec driver initialization)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  spmfw: {
    name: 'spmfw',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'System Power Manager firmware for SoC thermal and power domain management.',
    technicalRole: 'Monitors thermal zones and deep sleep idle power states to maximize battery longevity during screen-off intervals.',
    bootStage: 'Stage 1 / 2 (Power management setup)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  sspm: {
    name: 'sspm',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'Smart Sensor Power Manager firmware for low-power sensor hub orchestration.',
    technicalRole: 'Coordinates low-power sensor polling and manages subsystem sleep state wakeups without waking CPU cores.',
    bootStage: 'Stage 1 / 2 (Power management setup)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  pi_img: {
    name: 'pi_img',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'Power Island management firmware controlling independent power domains.',
    technicalRole: 'Selectively cuts power to idle SoC circuits (e.g. NPU, GPS, Camera) while keeping essential CPU cores operational.',
    bootStage: 'Stage 1 (Power island grid initialization)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  mcf_ota: {
    name: 'mcf_ota',
    category: 'firmware',
    groupLabel: 'MediaTek Baseband Firmware',
    summary: 'Modem Configuration File update binary for carrier aggregation.',
    technicalRole: 'Supplies regional carrier aggregation profiles, VoLTE configurations, and network operator frequency band tables.',
    bootStage: 'Stage 3 (Loaded during modem initialization)',
    avbStatus: 'Signed carrier payload',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  mcupm: {
    name: 'mcupm',
    category: 'firmware',
    groupLabel: 'MediaTek Subsystem Firmware',
    summary: 'Micro Controller Unit Power Management firmware.',
    technicalRole: 'Regulates CPU cluster voltage states and thermal power dissipation limits.',
    bootStage: 'Stage 1 (Power management startup)',
    avbStatus: 'Signed with MediaTek key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },
  logo: {
    name: 'logo',
    category: 'firmware',
    groupLabel: 'MediaTek Display Firmware',
    summary: 'Boot splash logo graphics buffer displayed during power-on.',
    technicalRole: 'Stores raw bitmap images rendered by Little Kernel (LK) during early boot before the Android kernel and surfaceflinger start.',
    bootStage: 'Stage 2 (Rendered by Little Kernel)',
    avbStatus: 'Signed with OEM key',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'MediaTek',
    archiveFile: '-image-firmware.7z',
  },

  // --- 5. PERSISTENT STORAGE & CONTROL STATE ---
  userdata: {
    name: 'userdata',
    category: 'data',
    groupLabel: 'Persistent Storage',
    summary: 'User data partition containing all apps, media, and encryption keys.',
    technicalRole: 'Formatted with F2FS / ext4 and encrypted via File-Based Encryption (FBE). Retained and never overwritten during A/B system updates.',
    bootStage: 'Stage 4 (Mounted after decryption via vold)',
    avbStatus: 'File-Based Encryption (FBE)',
    flashingMode: 'bootloader (fastboot)',
    chipset: 'Universal',
    archiveFile: 'Non-slotted',
    rootRelevance: 'Wiped during explicit factory reset or initial bootloader unlock.',
  },
  misc: {
    name: 'misc',
    category: 'data',
    groupLabel: 'Control State Buffer',
    summary: 'Hardware communication buffer between userspace and bootloader.',
    technicalRole: 'Holds the bootloader_message struct and boot_control HAL slot state metadata (active slot indicator, retry counter, recovery commands).',
    bootStage: 'Stage 1 / 2 (Read by bootloader to pick slot)',
    avbStatus: 'Raw sector buffer',
    flashingMode: 'non-flashable',
    chipset: 'Universal',
    archiveFile: 'Non-slotted',
  },
} satisfies Record<string, PartitionInfo>;

export type PartitionKey = keyof typeof PARTITIONS_DATA;

export const PARTITION_GROUPS: PartitionGroupConfig[] = [
  {
    id: 'firmware',
    title: '1. Chipset & Bootloader Firmware',
    isFirmwareContainer: true,
    keys: [
      // Qualcomm Snapdragon
      'abl', 'xbl', 'xbl_config', 'xbl_ramdump', 'tz', 'hyp', 'modem', 'dsp', 'keymaster', 'pvmfw', 'qupfw', 'uefi', 'uefisecapp', 'aop', 'aop_config', 'cpucp', 'cpucp_dtb', 'devcfg', 'featenabler', 'imagefv', 'shrm', 'bluetooth', 'multiimgoem', 'multiimgqti', 'qweslicstore', 'soccp_dcd', 'soccp_debug',
      // MediaTek Dimensity
      'preloader_raw', 'lk', 'tee', 'md1img', 'scp', 'apusys', 'gz', 'ccu', 'dpm', 'gpueb', 'vcp', 'spmfw', 'sspm', 'pi_img', 'mcf_ota', 'mcupm', 'logo', 'connsys_bt', 'connsys_wifi', 'connsys_gnss', 'audio_dsp', 'mvpu_algo'
    ],
  },
  {
    id: 'boot',
    title: '2. Kernel & Security Stack',
    keys: ['init_boot', 'boot', 'vendor_boot', 'dtbo', 'recovery', 'vbmeta', 'vbmeta_system', 'vbmeta_vendor'],
  },
  {
    id: 'logical',
    title: '3. Dynamic Logical Partitions (super.img)',
    isSuperContainer: true,
    superTitle: '3. Dynamic Logical Partitions (super.img)',
    description: 'System and OEM partitions pooled inside the dynamic super container:',
    keys: ['system', 'system_ext', 'product', 'vendor', 'odm', 'vendor_dlkm', 'system_dlkm', 'odm_dlkm'],
  },
  {
    id: 'data',
    title: '4. Persistent Data & Control State',
    badge: 'Non-slotted',
    keys: ['userdata', 'misc'],
  },
];

export const AB_STEPS: AbStepConfig[] = [
  {
    step: 1,
    title: '1. Active System Execution',
    badge: 'Slot A Active',
    activeSlot: 'A',
    targetSlot: 'B',
    statusA: 'Active (Running Nothing OS)',
    statusB: 'Standby / Prior Build Backup',
    operation: 'Normal execution from Slot A with system mounted read-only.',
    technicalDetails: 'The bootloader evaluates the /misc partition on startup. Slot A is designated as active, bootable, and successful. Storage partitions boot_a, init_boot_a, and super logical partitions are mounted read-only.',
    command: 'fastboot getvar current-slot => _a',
  },
  {
    step: 2,
    title: '2. Background Payload Streaming',
    badge: 'Writing Slot B',
    activeSlot: 'A',
    targetSlot: 'B',
    statusA: 'Active (In use)',
    statusB: 'Streaming payload chunks...',
    operation: 'update_engine downloads and writes OTA blocks directly into Slot B.',
    technicalDetails: 'Virtual A/B uses copy-on-write (COW) snapshots on userdata. The update_engine daemon writes delta payload blocks in the background without interrupting running apps.',
    command: 'update_engine: Applying payload to Slot B snapshots',
  },
  {
    step: 3,
    title: '3. Cryptographic Verification & Slot Switch',
    badge: 'Verification Pass',
    activeSlot: 'A',
    targetSlot: 'B',
    statusA: 'Active',
    statusB: 'Verified & Target Ready',
    operation: 'vbmeta_b signature validation and /misc slot flag handoff.',
    technicalDetails: 'Android validates cryptographic hash trees across all Slot B images using vbmeta_b. Upon verification, the boot_control HAL writes to /misc, setting Slot B as the active boot target with an initial retry counter of 7.',
    command: 'bootctl set-active-boot-slot 1',
  },
  {
    step: 4,
    title: '4. Restart & Automatic Rollback Guard',
    badge: 'Slot B Active',
    activeSlot: 'B',
    targetSlot: 'A',
    statusA: 'Rollback Standby',
    statusB: 'Running Updated System',
    operation: 'Quick restart into Slot B with update_verifier dm-verity confirmation.',
    technicalDetails: 'The device reboots into Slot B in seconds. Early init invokes update_verifier to confirm dm-verity filesystem integrity. Once verified, Slot B is marked successful. If boot fails after 7 retries, the bootloader automatically reverts to Slot A.',
    command: 'update_verifier: dm-verity verified -> Slot B marked successful',
  },
];

export const AOSP_DOC_LINKS: AospDocLink[] = [
  {
    title: 'Partitions Overview',
    url: 'https://source.android.com/docs/core/architecture/partitions',
    desc: 'AOSP specification for system, vendor, boot, and flash partitions.',
  },
  {
    title: 'Bootloader Architecture',
    url: 'https://source.android.com/docs/core/architecture/bootloader',
    desc: 'Cryptographic signature verification, kernel handover, and slot control.',
  },
  {
    title: 'Generic Kernel (GKI)',
    url: 'https://source.android.com/docs/core/architecture/kernel',
    desc: 'Modular Linux kernel architecture, init_boot separation, and driver HALs.',
  },
  {
    title: 'A/B System Updates',
    url: 'https://source.android.com/docs/core/ota/ab',
    desc: 'Dual-slot background update mechanics, state machine, and rollback guards.',
  },
  {
    title: 'Dynamic Partitions',
    url: 'https://source.android.com/docs/core/ota/dynamic_partitions',
    desc: 'Userspace dm-linear block allocation and super partition container.',
  },
];

export interface GlossaryTerm {
  term: string;
  subtitle: string;
  simpleMeaning: string;
  technicalRole: string;
}

export const PARTITION_GLOSSARY: GlossaryTerm[] = [
  {
    term: 'super.img',
    subtitle: 'Dynamic Partition Container',
    simpleMeaning: 'A single storage container that holds all Nothing OS system sub-partitions (system, vendor, product) in one shared space.',
    technicalRole: 'Physical flash partition housing metadata (liblp) that maps logical partitions dynamically at runtime.',
  },
  {
    term: 'dm-linear',
    subtitle: 'Virtual Partition Resizer',
    simpleMeaning: 'The Linux kernel driver that sizes each system sub-partition inside super.img on demand during updates.',
    technicalRole: 'Device-mapper target that concatenates physical block extents to construct resizable logical block devices.',
  },
  {
    term: 'FastbootD',
    subtitle: 'Userspace Partition Flasher',
    simpleMeaning: 'A Fastboot environment running in Android recovery that allows flashing individual dynamic partitions inside super.img.',
    technicalRole: 'Userspace Fastboot implementation running in recovery/ramdisk with full liblp and dm-linear kernel driver support.',
  },
  {
    term: 'AVB 2.0',
    subtitle: 'Android Verified Boot',
    simpleMeaning: 'A cryptographic security check that confirms system and kernel files match official signatures before booting.',
    technicalRole: 'Root-of-trust security architecture verifying RSA/ECC signatures across vbmeta descriptor hash trees.',
  },
  {
    term: 'dm-verity',
    subtitle: 'Live Integrity Scanner',
    simpleMeaning: 'A kernel security driver that blocks startup and stops tampering if any protected system block is modified.',
    technicalRole: 'Kernel target calculating transparent, real-time SHA-256 Merkle tree verification across read-only block devices.',
  },
  {
    term: 'Virtual A/B',
    subtitle: 'Dual-Slot Background Updates',
    simpleMeaning: 'Two partition sets (Slot A and Slot B) that let updates install in the background while you continue using your phone.',
    technicalRole: 'Dual-slot system update architecture with copy-on-write snapshotting to allow background updates and instant rollback protection.',
  },
  {
    term: 'COW Snapshots',
    subtitle: 'Copy-on-Write Update Storage',
    simpleMeaning: 'Temporary storage that records only modified update blocks on userdata instead of duplicating entire partition files.',
    technicalRole: 'Copy-on-write storage snapshot buffers created during OTA streaming and merged permanently upon successful boot verification.',
  },
];
