/**
 * Defines the hierarchical structure of the documentation sidebar.
 * Document IDs referenced here must map directly to Markdown filenames within `/docs`.
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Resources',
      collapsed: false,
      items: [
        'devices',
        'firmware',
        {
          type: 'category',
          label: 'OTA Changelogs',
          link: {
            type: 'generated-index',
            description: 'Official Nothing OS Update Changelogs for Respective Phone Models.',
            slug: '/changelogs',
          },
          items: [{ type: 'autogenerated', dirName: 'changelogs' }],
        },
        'guides',
        'official',
        'apps',
        'projects',
        'photography',
      ],
    },
  ],
};

export default sidebars;
