/**
 * Sidebar Configuration
 *
 * Defines the documentation sidebar structure.
 * Doc IDs must match filenames in /docs (without .md extension).
 */
import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  mainSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Resources',
      collapsed: false,
      items: ['devices', 'firmware', { type: 'category', label: 'OTA Changelogs', link: { type: 'generated-index', description: 'Nothing OS and CMF OTA Update Changelogs for all devices.', slug: '/changelogs' }, items: [{ type: 'autogenerated', dirName: 'changelogs' }] }, 'guides', 'official', 'apps', 'projects', 'photography'],
    },
  ],
};

export default sidebars;
